# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Kids_AR' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kids_At
	pod 'Firebase/Core'

  target 'Kids_ARTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Kids_ARUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
